version: '3.2'
services:
  identity-service:
    container_name: identity-service
    hostname: identity-service
    build: .
    ports:
      - "7000:80"
networks:
  default:
    name: services-network
    external: true