version: "3.2"
services:
  sql-server:
    container_name: sql-server
    hostname: sql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "MyStrongPassw0rd!"
      ACCEPT_EULA: "Y"
networks:
  default:
    name: services-network
    external: true